Prash logging
tomzig16/TemplateBot pull request #26
Opened 2021-09-18 13:20 UTC by prsh11

Add logging features.

2021-09-18 17:05 UTC, tomzig16 requested changes
Left quite a few comments to change and discuss.

Other than that, good functionality, pretty sure it will save our butt at one point in the future.

The only thing globally I want you to change is to be more consistent with function names. We use camelCase. `dev_env`, `current_time` and similar functions have snake case, while other places have camelCase. Please be consistent and use camelCase everywhere. (if you need more info about our code standards, look up [Contribution](https://github.com/tomzig16/TemplateBot/blob/master/docs/Misc/Guidelines/Contribution.md) docs inside `docs` folder )

2021-09-19 09:45 UTC, ACuteWoof submitted a review, later dismissed

2021-09-19 13:21 UTC, tomzig16 submitted a review, later dismissed
test_env and current_time still not changed (only prodEnv seems to me). + some more changes asked per line

2021-09-22 17:53 UTC, tomzig16 approved these changes

2021-09-23 15:08 UTC, merged